name: ibe_candidaturas
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  eva_icons_flutter: ^3.1.0
  fluttertoast: ^8.2.5
  file_picker: ^8.0.6
  dio: ^5.5.0+1
  menu_bar: ^0.5.3
  sqflite: ^2.3.3+1
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.3
  path_provider: ^2.1.4
  #workmanager: ^0.5.2
  #hive: ^2.2.3
  #hive_flutter: ^1.1.0
  #hive_generator: ^2.0.1
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^2.0.0
  #build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/

