name: ibe_candidaturas
description: App Portal do candidato, IBE-IP.
publish_to: 'none'
version: 0.1.0+8

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  eva_icons_flutter: ^3.1.0
  fluttertoast: ^8.2.5
  file_picker: ^8.0.6
  dio: ^5.5.0+1
  menu_bar: ^0.5.3
  #sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_uploader: ^3.0.0-beta.4
  connectivity_plus: ^6.0.5
  flutter_background_service: ^5.0.10
  awesome_notifications: ^0.9.3+1

  device_preview: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.3.1
  iconsax: ^0.0.8
  ionicons: ^0.2.2
  path_provider: ^2.1.4
  open_filex: ^4.5.0
  panara_dialogs: ^0.1.5
  #flutter_boxicons: ^3.1.0

flutter_launcher_icons:
  android: true #"launcher_icon"
  image_path_android: "assets/images/icon.png"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 16 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    #background_color: "#hexcode"
    #theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 38 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^2.0.0
  #build_runner: ^2.4.11
  #flutter_app_name: ^0.1.0
flutter_app_name:
  name: "Portal do Candidato"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

